name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Set execution permission for deploy.sh
        run: chmod +x deploy.sh

      - name: Run deployment script
        run: ./deploy.sh

      - name: Deploy to GitHub Pages
        run: |
          git checkout -b gh-pages
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
